language: node_js
node_js:
  - "10"
addons:
  chrome: stable
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
	- sleep 3
script:
  - npm run lint
  - npm run test
  - npm run build
branches:
  only:
    - master
