language: node_js
node_js:
  - "10"
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - sleep 3
script:
  - npm run lint
  - npm run test
  - npm run build
branches:
  only:
    - master
